substitutions:
  _IMAGE_NAME: ss-wrapper-service
  _GCS_CACHE_BUCKET: central-mvn-cache-rckms
steps:
  # load the cache from GCS if it exists
  - name: gcr.io/cloud-builders/gsutil
    dir: /root
    entrypoint: bash
    args:
      - -c
      - |
        (
          gsutil cp gs://${_GCS_CACHE_BUCKET}/${_IMAGE_NAME}-m2-cache-${BRANCH_NAME}.tar.gz /tmp/${_IMAGE_NAME}-m2-cache-${BRANCH_NAME}.tar.gz &&
          tar -xzf /tmp/${_IMAGE_NAME}-m2-cache-${BRANCH_NAME}.tar.gz
        ) || echo 'Cache not found'
    volumes:
      - name: m2
        path: /root/.m2
  - name: gcr.io/cloud-builders/mvn
    id: build
    args:
      [ "clean", "install", "jib:build", "-DskipTests", "-Dimage=gcr.io/${PROJECT_ID}/${_IMAGE_NAME}:${BRANCH_NAME}" ]
    volumes:
      - name: m2
        path: /root/.m2
  # cache the /root/.m2 folder and upload it to GCS bucket
  - name: gcr.io/cloud-builders/gsutil
    waitFor:
      - build
    dir: /root
    entrypoint: bash
    args:
      - -c
      - |
        tar -czf /tmp/${_IMAGE_NAME}-m2-cache-${BRANCH_NAME}.tar.gz .m2 &&
        gsutil cp /tmp/${_IMAGE_NAME}-m2-cache-${BRANCH_NAME}.tar.gz gs://${_GCS_CACHE_BUCKET}/${_IMAGE_NAME}-m2-cache-${BRANCH_NAME}.tar.gz
    volumes:
      - name: m2
        path: /root/.m2